#!/usr/bin/env python3
"""Turn cahyadsn/wilayah's MySQL dump into a D1 (SQLite) seed.

Source: https://github.com/cahyadsn/wilayah — MIT, tracking Kepmendagri 300.2.2-2430/2025.
We do NOT use any 34-province list: BMKG has moved to the post-2022 codes, so the old Merauke
code 91.01.01.2001 returns 404 upstream while the current 93.01.01.2001 returns the same
village. See "The Papua problem" in README.md.

Output:
  data/wilayah.seed.sql   — schema + multi-row INSERTs, ready for `wrangler d1 execute --file`
"""
from __future__ import annotations

import re
import sys
import unicodedata
import urllib.request
from pathlib import Path

SOURCE = "https://raw.githubusercontent.com/cahyadsn/wilayah/master/db/wilayah.sql"
ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "data" / "wilayah.source.sql"
OUT = ROOT / "data" / "wilayah.seed.sql"

# Rows per INSERT. Keeps the file small without blowing SQLite's statement limits.
ROWS_PER_INSERT = 400

TUPLE_RE = re.compile(r"\('((?:[^']|'')*)','((?:[^']|'')*)'\)")


def fetch() -> str:
    if CACHE.exists():
        return CACHE.read_text(encoding="utf-8")
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(SOURCE) as r:
        text = r.read().decode("utf-8")
    CACHE.write_text(text, encoding="utf-8")
    return text


def unquote(s: str) -> str:
    return s.replace("''", "'").replace("\\'", "'").strip()


def normalise(name: str) -> str:
    """Uppercase, strip accents and punctuation. What search matches against."""
    folded = unicodedata.normalize("NFKD", name)
    folded = "".join(c for c in folded if not unicodedata.combining(c))
    folded = folded.upper()
    return re.sub(r"[^A-Z0-9 ]+", " ", folded).strip()


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> int:
    raw = fetch()
    rows: list[tuple[str, str, int, str | None, str]] = []
    seen: set[str] = set()

    for kode, nama in TUPLE_RE.findall(raw):
        kode = unquote(kode)
        nama = unquote(nama)
        if not kode or kode in seen:
            continue
        seen.add(kode)
        level = kode.count(".") + 1
        if level not in (1, 2, 3, 4):
            continue
        parent = kode.rsplit(".", 1)[0] if level > 1 else None
        rows.append((kode, nama, level, parent, normalise(nama)))

    if not rows:
        print("no rows parsed — the upstream dump format changed", file=sys.stderr)
        return 1

    # One row per (code, word) so search is an index range scan, never a table scan.
    # A full scan would read 91k rows per query and burn the free tier in ~55 searches a day.
    tokens: list[tuple[str, str]] = []
    for kode, _nama, _level, _parent, norm in rows:
        for word in {w for w in norm.split() if len(w) > 1}:
            tokens.append((kode, word))

    by_level: dict[int, int] = {}
    for _, _, level, _, _ in rows:
        by_level[level] = by_level.get(level, 0) + 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        f.write("-- generated by tools/build-wilayah.py — do not edit\n")
        f.write(f"-- source: {SOURCE}\n")
        f.write(f"-- regions: {len(rows)}  tokens: {len(tokens)}\n\n")
        f.write("DROP TABLE IF EXISTS wilayah_token;\n")
        f.write("DROP TABLE IF EXISTS wilayah;\n")
        f.write(
            "CREATE TABLE wilayah (\n"
            "  kode      TEXT PRIMARY KEY,\n"
            "  nama      TEXT NOT NULL,\n"
            "  level     INTEGER NOT NULL,\n"
            "  parent    TEXT,\n"
            "  nama_norm TEXT NOT NULL\n"
            ");\n"
            "CREATE INDEX idx_wilayah_parent ON wilayah(parent);\n"
            "CREATE INDEX idx_wilayah_level  ON wilayah(level);\n"
            "CREATE INDEX idx_wilayah_norm   ON wilayah(nama_norm);\n\n"
            "CREATE TABLE wilayah_token (\n"
            "  token TEXT NOT NULL,\n"
            "  kode  TEXT NOT NULL\n"
            ");\n"
            "CREATE INDEX idx_token ON wilayah_token(token, kode);\n\n"
        )

        def emit(table: str, cols: str, values: list[str]) -> None:
            for i in range(0, len(values), ROWS_PER_INSERT):
                chunk = values[i : i + ROWS_PER_INSERT]
                f.write(f"INSERT INTO {table} {cols} VALUES\n")
                f.write(",\n".join(chunk))
                f.write(";\n")

        emit(
            "wilayah",
            "(kode,nama,level,parent,nama_norm)",
            [
                "({},{},{},{},{})".format(
                    sql_str(k), sql_str(n), lv, sql_str(p) if p else "NULL", sql_str(nn)
                )
                for k, n, lv, p, nn in rows
            ],
        )
        emit(
            "wilayah_token",
            "(token,kode)",
            [f"({sql_str(t)},{sql_str(k)})" for k, t in tokens],
        )

    size_mb = OUT.stat().st_size / 1_048_576
    print(f"regions   : {len(rows)}")
    print(f"  level 1 : {by_level.get(1, 0)} provinces")
    print(f"  level 2 : {by_level.get(2, 0)} kabupaten/kota")
    print(f"  level 3 : {by_level.get(3, 0)} kecamatan")
    print(f"  level 4 : {by_level.get(4, 0)} desa/kelurahan")
    print(f"tokens    : {len(tokens)}")
    print(f"seed      : {OUT.relative_to(ROOT)}  ({size_mb:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
